%Vector_1way_CntlG.m  

% Copyright C 2009  Thomas A. Jones.  All rights reserved.
% Everyone is granted permission to copy, modify, and redistribute
% this program, but under the condition that this copyright notice
% remain intact and the Computers & Geosciences source be referenced. 
% This software has been tested extensively, but is distributed 
% WITHOUT ANY WARRANTY.  The author does not accept responsibility
% for any possible consequences of using it.

% GUI that obtains the controls that specify/define dataset to be used. 
% This specifies the test and entries on the screen for user control.

% Variables to be obtained and defaults:
%   NSkipHdr=0: Number of headers on data file to be skipped
%   NRows=0: Number of rows in data file (excluding headers)
%   NCols=0: Number of columns in data file
%   UseFrq = 0: Read individual azimuths (0) or count-freq (1) data
%   MissData = -99:  If indiv. azimuths, indicates missing data when
%            groups don't have equla counts
%   WrOut = 1: Write results to external file (1=No, 0=Yes)
%   DegRad = 0: Input azimuths in degrees (0) or radians (1)
%   Data_Array='AzData' or '': Name of input array that contains data
%   RtrnCode = 0: Error return

% Set up the figure

Hfig_GUI = figure;       % Handle to figure window

set(Hfig_GUI, 'NumberTitle', 'off', ...
    'Color',[0.9, 0.9, 0.9], ...
    'Name','Specify dataset/job controls', ...
    'Menubar','none', ...
    'Units','inches',  ...
    'Position', [0.3, 2.4, 4.7, 3.8]);

% Set up the entries

if datatype == 1
   
HL_1 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 23, 50, 2], ...
    'String','Number of header records (rows) to skip');
HT_1 = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[70, 23, 8, 2], ...
    'String',num2str(NSkipHdr), ...
    'Callback','NSkipHdr = str2num(get(HT_1,''String''));');

HL_NC = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 20, 50, 2], ...
    'String','Number of columns in file');
HT_NC = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[70, 20, 8, 2], ...
    'String',num2str(NCols), ...
    'Callback','NCols = str2num(get(HT_NC,''String''));');

else
    
HL_DAr = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 21, 60, 2], ...
    'String','Specify name of data array to be used');
HT_DAr = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[65, 21, 15, 2], ...
    'String', Data_Array, ...
    'Callback','Data_Array = get(HT_DAr,''String'');');
    
end

HL_DR1 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 17, 45, 2], ...
    'String','Input data in Degrees or Radians?');
HT_DR2 = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[55, 17, 10, 2], ...
    'String', 'DEGR.', ...
    'Callback','DegRad = str2num(''0'');');
HT_DR3 = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[69, 17, 10, 2], ...
    'String', 'Rad.', ...
    'Callback','DegRad = str2num(''1'');');

HL_Fr1 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 12, 30, 3], ...
    'String','Input as azimuths or frequency distributions?');
HT_Fr2 = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[52, 12.5, 13, 2], ...
    'String', 'AZIMUTH', ...
    'Callback','UseFrq = str2num(''0'');');
HT_Fr3 = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[69, 12.5, 13, 2], ...
    'String', 'Freq. Dist.', ...
    'Callback','UseFrq = str2num(''1'');');

HL_MD = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 8, 40, 3], ...
    'String','Value used for missing data (non-equal sample sizes)');
HT_MD = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[70, 8.5, 8, 2], ...
    'String',num2str(MissData), ...
    'Callback','MissData = str2num(get(HT_MD,''String''));');
                      
HL_OFIL1 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 5, 45, 2], ...
    'String','Write summary of job to output file?');
HT_OFIL2 = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[57, 5, 10, 2], ...
    'String', 'Yes', ...
    'Callback','WrOut = str2num(''0'');');
HT_OFIL3 = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[72, 5, 10, 2], ...
    'String', 'NO', ...
    'Callback','WrOut = str2num(''1'');');

HPushCls = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 1, 10, 2], ...
    'String','OK', ...
    'Callback','RtrnCode = str2num(''0'');close;');
HPushCncl = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[72, 1, 10, 2], ...
    'String','Cancel', ...
    'Callback','RtrnCode = str2num(''8'');close;');

uiwait

