function OUT = PHOT_read_csv_from_digilent(file_path_and_name)
% function OUT = PHOT_read_csv_from_digilent(file_path_and_name)
%
% Reads the .csv files generated by the Digilent Analog Discovery 2
% Oscilloscope.
%
% Cowen 2024
%
% for testing
% file_path_and_name{1} = 'C:\Temp\001_Amphetamine Injection.csv';
% PHOT_read_csv_from_digilent(file_path_and_name)
if nargin == 0
    % if nothing in the input, assume you want all csv files in the current
    % directory.
    file_path_and_name = FindFiles('*.csv');
end
PLOT_IT = false;
if nargout == 0
    PLOT_IT = true;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if ~iscell (file_path_and_name)
    % If the user gives a single filename (e.g., 'C:\Temp\abc.csv') then
    % make it into a cell array.
    tmp = file_path_and_name;
    file_path_and_name = [];
    file_path_and_name{1} = tmp;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for iF = 1:length(file_path_and_name)
    OUT(iF).fname = file_path_and_name{iF};
    OUT(iF).Data = readtable(file_path_and_name{iF});
    fp = fopen(file_path_and_name{iF},'r');
    for ii = 1:18
        OUT(iF).header{ii} = fgetl(fp);
    end
    fclose(fp);
end

if PLOT_IT
    for iF = 1:length(OUT)
        v_names = OUT(iF).Data.Properties.VariableNames;
        figure
        plot(OUT(iF).Data.Time_s_, OUT(iF).Data.Channel1_V_)
        hold on
        plot(OUT(iF).Data.Time_s_, OUT(iF).Data.Channel2_V_)
        xlabel(v_names{1})
        ylabel([v_names{2} ' ' v_names{3}])
        title(OUT(iF).fname)
        axis tight
    end
end