function [F] = SPEC_create_filters(filtbandname, sFreq)
%
default_order = 12;
PLOT_IT = false;
OSC = Oscillation_frequencies;
if ischar(filtbandname) || isnumeric(filtbandname)
    filtbandname = {filtbandname};
end

F = cell(length(filtbandname),1);

for ii = 1:length(filtbandname)
    if isnumeric(filtbandname{ii})
        F{ii} = designfilt('bandpassiir','FilterOrder',default_order, ...
            'HalfPowerFrequency1',filtbandname{ii}(1),'HalfPowerFrequency2',filtbandname{ii}(2), ...
            'SampleRate',sFreq);
    else
        
        switch filtbandname{ii}
            case 'delta'      
                F{ii} = designfilt('bandpassiir','FilterOrder',10, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'theta'
          
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'beta'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'beta2'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);            
            case 'beta3'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'low_gamma'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'low_gamma_colgin'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'low_gamma2'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'low_gamma_fenton'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'med_gamma_fenton'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'high_gamma'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'fast_gamma'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
                
            case 'high_gamma_lindsey'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'gamma_50'
                F{ii} = designfilt('bandpassiir','FilterOrder',18, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'gamma_80'
                F{ii} = designfilt('bandpassiir','FilterOrder',28, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'HFO'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);           
            case 'ripple'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'ripple_young'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            case 'user_defined'
                F{ii} = designfilt('bandpassiir','FilterOrder',12, ...
                    'HalfPowerFrequency1',OSC.(filtbandname{ii})(1),'HalfPowerFrequency2',OSC.(filtbandname{ii})(2), ...
                    'SampleRate',sFreq);
            otherwise
                error('no known freq specified')
        end
    end
    if PLOT_IT
        freqz(F{ii},[],sFreq)
    end
end