Document and data roadmap

react1.xls - Excell spreadsheet of the reactivation data (20ms bin) for 3 rats. These are the 
  same data as found in react1.mat.
react1.mat - Matlab data file for reactivation for 24 datasets(3 rats) binned at 20ms-- only ripples.
react2.mat - Matlab data file for reactivation for 24 datasets(3 rats) binned at 20ms-- inter ripples(all of inter_ripple).
react3.mat - React in all sleep and just interrip maze.
react4.mat - Looking at pref reactivation in the inter-ripple periods with same mean duration as ripple periods.
        