function S = Session_info(varargin)
% Create a cell array of the large data sets
%
% INPUT: the projects you wish to load the data for,
%
% OUTPUT: Cell array of data sets.
%
% Note: to print out this data, see Print_session_info

% cowen Mon Mar 29 17:57:41 1999

% The essential data directories.
TRUE = 1; 
FALSE = 0;
NEITHER = 999;
GOOD= 1;
AVG = 2;
BAD = 3;
UGLY= 4;
if findstr(computer,'PCWIN')
    OSTData = fullfile(Data_dir,'Operant_Spike_Training',filesep);
    Hyper5Data = fullfile(Data_dir,'Hyper 5',filesep);
    Hyper4Data = fullfile(Data_dir,'Hyper 4',filesep);
    StressData = fullfile(Data_dir,'Startle',filesep);
    BowerData = fullfile(Data_dir,'Bower_Lights',filesep);
    MoserData = fullfile(Data_dir,'Moser',filesep);
    Datadir2 = fullfile(Data_dir, filesep);
else
    OSTData = fullfile(Data_dir,'Operant_Spike_Training',filesep);
    Hyper5Data = fullfile(Data_dir,'Hyper 5',filesep);
    Hyper4Data = fullfile(Data_dir,'Hyper 4',filesep);
    StressData = fullfile(Data_dir,'Startle',filesep);
    BowerData = fullfile(Data_dir,'Bower_Lights',filesep);
    MoserData = fullfile(Data_dir,'Moser',filesep);
    Datadir2 = fullfile(Data_dir, filesep);
end

T = 1;
% New data.
S(1) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_01'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',1,'nepochs',5,'sleep_qual',GOOD,'note','');
S(2) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_02'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(3) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_03'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(4) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_04'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',0,'nepochs',5,'sleep_qual',BAD,'note','');
S(5) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_05'),'pcorrect',2/10,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',FALSE,'iscut',TRUE ,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(6) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_06'),'pcorrect',6/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(7) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_07'),'pcorrect',5/9,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ...
,'bigfirst',1,'nepochs',5,'sleep_qual',GOOD,'note','');
S(8) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_08'),'pcorrect',9/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','finally switched to curtain on probes');
S(9) = struct('data_dir',fullfile(Hyper5Data,'6429','6429_09'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE ,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(10)= struct('data_dir',fullfile(Hyper5Data,'6429','6429_10'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',NEITHER,'iscut',FALSE,'bigfirst',9,'nepochs',1,'sleep_qual',0,'note','REM recording, not smsms');
S(11)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_02'),'pcorrect',6/6,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',0,'nepochs',5,'sleep_qual',GOOD,'note',''); 
S(12)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_03'),'pcorrect',2/3,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note',''); 
S(13)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_04'),'pcorrect',6/9,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(14)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_05'),'pcorrect',4/4,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',1,'nepochs',5,'sleep_qual',GOOD,'note',''); 
S(15)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_06'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note',''); 
S(16)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_07'),'pcorrect',5/10,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(17)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_08'),'pcorrect',8/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE,'bigfirst',0,'nepochs',5,'sleep_qual',GOOD,'note',''); 
S(18)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_09'),'pcorrect',9/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',FALSE,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note',''); 
S(19)= struct('data_dir',fullfile(Hyper5Data,'6436','6436_10'),'pcorrect',10/10,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note',''); 
S(20)= struct('data_dir',fullfile(Hyper5Data,'6481','6481_01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note','');
S(21)= struct('data_dir',fullfile(Hyper5Data,'6481','6481_02'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note',''); 
S(22)= struct('data_dir',fullfile(Hyper5Data,'6481','6481_03'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note',''); 
S(23)= struct('data_dir',fullfile(Hyper5Data,'6481','6481_04'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',BAD,'note','');
S(24)= struct('data_dir',fullfile(Hyper5Data,'6481','6481_05'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note',''); 
S(25)= struct('data_dir',fullfile(Hyper5Data,'6481','6481_06'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note',''); 
S(26)= struct('data_dir',fullfile(Hyper5Data,'6481','6481_07'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',GOOD,'note','');
S(27)= struct('data_dir',fullfile(Hyper5Data,'6481','6481_08'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note',''); 
S(28)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_01'),'pcorrect',9/10,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',1,'nepochs',5,'sleep_qual',GOOD,'note','');
S(29)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_02'),'pcorrect',9/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(30)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_03'),'pcorrect',10/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(31)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_04'),'pcorrect',10/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',0,'nepochs',5,'sleep_qual',GOOD,'note','Out of control EV');
S(32)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_05'),'pcorrect',0/10,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',FALSE,'iscut',TRUE ,'bigfirst',1,'nepochs',5,'sleep_qual',0,'note','');
S(33)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_06'),'pcorrect',3/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(34)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_07'),'pcorrect',6/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ,'bigfirst',1,'nepochs',5,'sleep_qual',UGLY,'note','');
S(35)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_08'),'pcorrect',9/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',TRUE ,'bigfirst',0,'nepochs',5,'sleep_qual',0,'note','');
S(36)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_09'),'pcorrect',9/10,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',FALSE,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',0,'note',''); 
S(37)= struct('data_dir',fullfile(Hyper5Data,'6568','6568_10'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',NEITHER,'iscut',FALSE,'bigfirst',9,'nepochs',1,'sleep_qual',0,'note','REM Sleep test not SMSMS'); 

S(38)= struct('data_dir',fullfile(Hyper5Data,'6610','6610_01'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',0,'iscut',TRUE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note',''); 
S(39)= struct('data_dir',fullfile(Hyper5Data,'6610','6610_02'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note',''); 
S(40)= struct('data_dir',fullfile(Hyper5Data,'6610','6610_03'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note',''); 
S(41)= struct('data_dir',fullfile(Hyper5Data,'6610','6610_04'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note',''); 
S(42)= struct('data_dir',fullfile(Hyper5Data,'6610','6610_05'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note',''); 
S(43)= struct('data_dir',fullfile(Hyper5Data,'6610','6610_06'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note',''); 
S(44)= struct('data_dir',fullfile(Hyper5Data,'6610','6610_07'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note',''); 
S(45)= struct('data_dir',fullfile(Hyper5Data,'6610','6610_08'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',1,'note',''); 
% Redo.
S(46)= struct('data_dir',fullfile(Hyper5Data,'6594','6594_01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',0,'iscut',TRUE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note',''); 
S(47)= struct('data_dir',fullfile(Hyper5Data,'6594','6594_02'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',0,'iscut',TRUE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note',''); 
S(48)= struct('data_dir',fullfile(Hyper5Data,'6594','6594_03'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note',''); 
S(49)= struct('data_dir',fullfile(Hyper5Data,'6594','6594_04'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',0,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note',''); 
S(50)= struct('data_dir',fullfile(Hyper5Data,'6594','6594_05'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note',''); 
S(51)= struct('data_dir',fullfile(Hyper5Data,'6594','6594_06'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note',''); 
S(52)= struct('data_dir',fullfile(Hyper5Data,'6594','6594_07'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note',''); 
S(53)= struct('data_dir',fullfile(Hyper5Data,'6594','6594_08'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',1,'iscut',FALSE,'bigfirst',9,'nepochs',5,'sleep_qual',3,'note',''); 

% old order

% Old Data from Hemant. Used for Poster 98

% !! I am not sure if these are old or young rats.
S(61)= struct('data_dir',fullfile(Datadir2, '5672_07'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note','');% 
S(62)= struct('data_dir',fullfile(Datadir2, '5672_08'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note','');% 
S(63)= struct('data_dir',fullfile(Datadir2, '5672_09'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note','');% 
S(64)= struct('data_dir',fullfile(Datadir2, '6207_01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note','');% 
S(65)= struct('data_dir',fullfile(Datadir2, '6207_02'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note',''); 
S(66)= struct('data_dir',fullfile(Datadir2, '6207_03'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note',''); 
S(67)= struct('data_dir',fullfile(Datadir2, '6207_14'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note',''); 
S(68)= struct('data_dir',fullfile(Datadir2, '6207_15'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note',''); 
S(69)= struct('data_dir',fullfile(Datadir2, '5631_08'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note',''); 
S(70)= struct('data_dir',fullfile(Datadir2, '5631_10'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note',''); 
S(71)= struct('data_dir',fullfile(Datadir2, '5358_05'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',TRUE,'iscut',TRUE ,'bigfirst',9,'nepochs',3,'sleep_qual',0,'note','');  

% Some of Mark's Sample cortical data
S(72)= struct('data_dir',fullfile(Hyper5Data, 'Mark_ctx_data'),'pcorrect',nan,'isold',999,...
    'isnovel',999,'isdoor_reward',999,'iscut',TRUE ...
,'bigfirst',9,'nepochs',3,'sleep_qual',99,'note','999 means unknown');  

% Hyper 4 data
S(80)= struct('data_dir',fullfile(Hyper4Data,'6504','6504ct01'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',TRUE,'bigfirst',999,'nepochs',3,'sleep_qual',999,'note',''); 

S(81)= struct('data_dir',fullfile(Hyper4Data,'6650','6650ct01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',TRUE,'bigfirst',999,'nepochs',3,'sleep_qual',999,'note',''); 

S(82)= struct('data_dir',fullfile(Hyper4Data,'6682','6682ct01'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',TRUE,'bigfirst',999,'nepochs',3,'sleep_qual',999,'note',''); 

S(83)= struct('data_dir',fullfile(Hyper4Data,'6682','6682ct08'),'pcorrect',nan,'isold',TRUE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE,'bigfirst',999,'nepochs',3,'sleep_qual',999,'note',''); 

S(84)= struct('data_dir',fullfile(Hyper4Data,'6792','6792ct01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',99,'iscut',TRUE,'bigfirst',999,'nepochs',3,'sleep_qual',999,'note',''); 

% STRESS!! The stress experiments:
S(101) = struct('data_dir',fullfile(StressData, '6989','6989_01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(102) = struct('data_dir',fullfile(StressData, '6989','6989_02'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(103) = struct('data_dir',fullfile(StressData, '6989','6989_03'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(104) = struct('data_dir',fullfile(StressData, '6989','6989_04'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(105) = struct('data_dir',fullfile(StressData, '6989','6989_05'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','Stressor');  
S(106) = struct('data_dir',fullfile(StressData, '6989','6989_06'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(107) = struct('data_dir',fullfile(StressData, '6989','6989_07'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(108) = struct('data_dir',fullfile(StressData, '6989','6989_08'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','Stressor');  
S(109) = struct('data_dir',fullfile(StressData, '6951','6951_11'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(110) = struct('data_dir',fullfile(StressData, '6951','6951_12'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(111) = struct('data_dir',fullfile(StressData, '6951','6951_13'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(112) = struct('data_dir',fullfile(StressData, '6951','6951_14'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','Stressor');  
S(113) = struct('data_dir',fullfile(StressData, '6951','6951_15'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(114) = struct('data_dir',fullfile(StressData, '6951','6951_16'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',TRUE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(115) = struct('data_dir',fullfile(StressData, '7050','7050_01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(116) = struct('data_dir',fullfile(StressData, '7050','7050_02'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(117) = struct('data_dir',fullfile(StressData, '7050','7050_03'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(118) = struct('data_dir',fullfile(StressData, '7050','7050_04'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(119) = struct('data_dir',fullfile(StressData, '7050','7050_05'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(120) = struct('data_dir',fullfile(StressData, '7050','7050_06'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(121) = struct('data_dir',fullfile(StressData, '7050','7050_07'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(122) = struct('data_dir',fullfile(StressData, '7050','7050_08'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(123) = struct('data_dir',fullfile(StressData, '7050','7050_09'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(124) = struct('data_dir',fullfile(StressData, '7050','7050_10'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(125) = struct('data_dir',fullfile(StressData, '7050','7050_11'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',FALSE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  

S(129) = struct('data_dir',fullfile(StressData, '7121','7121_01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel',TRUE,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(130) = struct('data_dir',fullfile(StressData, '7121','7121_02'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(131) = struct('data_dir',fullfile(StressData, '7121','7121_03'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(132) = struct('data_dir',fullfile(StressData, '7121','7121_04'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(133) = struct('data_dir',fullfile(StressData, '7121','7121_05'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(134) = struct('data_dir',fullfile(StressData, '7121','7121_06'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(135) = struct('data_dir',fullfile(StressData, '7121','7121_07'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(136) = struct('data_dir',fullfile(StressData, '7121','7121_08'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(137) = struct('data_dir',fullfile(StressData, '7121','7121_09'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(138) = struct('data_dir',fullfile(StressData, '7121','7121_10'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(139) = struct('data_dir',fullfile(StressData, '7121','7121_11'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(140) = struct('data_dir',fullfile(StressData, '7121','7121_12'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  
S(141) = struct('data_dir',fullfile(StressData, '7121','7121_13'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',5,'sleep_qual',999,'note','');  

S(142) = struct('data_dir',fullfile(BowerData, '7026_98'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','bower');  
S(143) = struct('data_dir',fullfile(BowerData, '7026_100'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','bower');  
S(144) = struct('data_dir',fullfile(BowerData, '7026_102'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','bower');  
S(145) = struct('data_dir',fullfile(BowerData, '7026_92'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','bower');  
S(146) = struct('data_dir',fullfile(BowerData, '7026_80'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','bower');  
S(147) = struct('data_dir',fullfile(BowerData, '7026_83'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','bower');  
S(148) = struct('data_dir',fullfile(BowerData, '7026_87'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','bower');  

S(200) = struct('data_dir',fullfile(MoserData, '6978_09'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(201) = struct('data_dir',fullfile(MoserData, '6978_10'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(202) = struct('data_dir',fullfile(MoserData, '6978_11'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(203) = struct('data_dir',fullfile(MoserData, '6978_12'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(204) = struct('data_dir',fullfile(MoserData, '7144_06'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(205) = struct('data_dir',fullfile(MoserData, '6978_01'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(206) = struct('data_dir',fullfile(MoserData, '6978_02'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(207) = struct('data_dir',fullfile(MoserData, '6978_03'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(208) = struct('data_dir',fullfile(MoserData, '6978_04'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(209) = struct('data_dir',fullfile(MoserData, '6978_05'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(210) = struct('data_dir',fullfile(MoserData, '6978_06'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(211) = struct('data_dir',fullfile(MoserData, '6978_07'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
S(212) = struct('data_dir',fullfile(MoserData, '6978_08'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','Moser');  
%%%%%%%%%%%%%%%%
S(250) = struct('data_dir',fullfile(OSTData, '7353_09'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','');  
S(251) = struct('data_dir',fullfile(OSTData, '7353_15_1'),'pcorrect',nan,'isold',FALSE,...
    'isnovel', nan,'isdoor_reward',999,'iscut',FALSE ,'bigfirst',9,'nepochs',3,'sleep_qual',999,'note','');  

foundit = 0;
% Return the datasets in question.
if nargin == 1
    % find the datasets in question
    if isa(varargin{1},'double')
        if varargin{1} > 5000
            % The use passed values such as 7050 1
            for jj = 1:length(varargin{1})
                t = num2str(varargin{1}(jj));
                tmp{jj} = [t(1:4) '_' t(5:end)];
            end
            varargin{1} = tmp;
        else
            % The use passed in an index into S (legacy)
            for jj = 1:length(varargin{1})
                [p,n,e] = fileparts(S(varargin{1}(jj)).data_dir);
                tmp{jj} = n;
            end
            varargin{1} = tmp;
        end
    elseif isempty(findstr('_',varargin{1}{1}))
        % If in 706401 format, convert over.
        for jj = 1:length(varargin{1})
            t = num2str(varargin{1}{jj});
            varargin{1}{jj} = [t(1:4) '_' t(5:end)];
        end
    end    
    for ii = 1:length(varargin{1})
        for jj = 1:length(S)
            if ~isempty(S(jj).data_dir)
                [a_p, a_name] = fileparts(S(jj).data_dir);
                if strcmp(varargin{1}{ii}, a_name)
                    O(ii) = S(jj);
                    fprintf('%s\t', varargin{1}{ii})
                    foundit = 1;
                    break
                end
            end
        end
    end
    if ~foundit
        error('Could not find file')
    end

    S = O;
end
