function [symbols, colors] = get_symbols()
colors = {'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y' ...
    'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y'  ...
    'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y'  ...
    'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y'  ...
    'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y'  ...
    'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y'  ...
    'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y'  ...
    'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y'  ...
    'b' 'r' 'g' 'c' 'k' 'm' 'y' 'b' 'r' 'g' 'c' 'k' 'm' 'y'  ...
     };
symbols = { 'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
    'bo' 'r*' 'g+' 'cp' 'k^' 'mx' 'yp' 'r>' 'g<' 'b*' 'co' 'k+' 'mp' 'yx' ...
  };
