function Plot_tsds(crtsd_array, startpt, windowsize, ylimit, staggar)
% Plot multiple tsds. Used by View_EEG
%
% INPUT: 
%     crtsd_array = cell array of tsds to plot. If the tsd is simply a list of
%     timestamps(as ts object) then a raster is printed. If it is
%     data, then the data is plotted
%    
%     startpt = point from which to begin the plot.
%
%  windowsize = size of the moving window (in seconds). Default is 1sec.
%
%     ylimit  = size of the y axes on the plot(+ and - y limit)
%
% This function is vital for View_EEG.m
%

% cowen Sat May  8 10:37:39 1999

if nargin == 3
  ylimit = 300;
end
if nargin <= 4
  staggar = 50;
end

colors = {'b' 'g' 'c' 'm' 'r' 'b' 'g' 'r' 'm' 'y' 'b' 'g' 'c' 'm' ...
    'r' 'y' 'g' 'm' 'r' 'y' 'b' 'g' 'c' 'b' 'r' 'y' 'g' 'm' 'r' ...
    'y' 'b' 'g' 'c' 'y' 'r' 'y' 'g' 'c' 'r' 'y' 'b' 'g' 'c' 'm' ...
    'y' 'b' 'g' 'c' 'y' 'r' 'y' 'g' 'c' 'r' 'y' 'b' 'g' 'c' 'm' ...
    'y' 'b' 'g' 'c' 'y' 'r' 'y' 'g' 'c' 'r' 'y' 'b' 'g' 'c' 'm' ...
    'y' 'b' 'g' 'c' 'y' 'r' 'y' 'g' 'c' 'r' 'y' 'b' 'g' 'c' 'm' ...
    'r' 'y' 'g' 'c' 'r' 'y' 'b' 'g' 'c' 'b:' 'r' 'y' 'g' 'm' 'r' 'y'};
symbols = {'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro', ...
    'ro','g>','<m','xr','>r','>m','+g','bx','ro' };
cntts = 1;
cnttsd = 1;
for cr = 1:length(crtsd_array)
  % if it's a ts object then print rasters
  if strcmp(class(crtsd_array{cr}),'ts') 
    z = zeros(size(Data(Restrict(crtsd_array{cr},startpt,startpt+windowsize))));
    z(:) = 0 - staggar .* cntts/5;

    if ~isempty(z)
      plot(Data(Restrict(crtsd_array{cr},startpt,startpt+windowsize)),z,symbols{cntts})
      cntts = cntts + 1;
    end
    
  else
    % Don't print if its empty
    if ~isempty(crtsd_array{cr})
      plot(Range(Restrict(crtsd_array{cr}, ...
	  startpt,startpt+windowsize),'ts'),Data(Restrict(crtsd_array{cr}, ...
	  startpt,startpt+windowsize))+staggar*cnttsd,colors{cnttsd})
      cnttsd = cnttsd + 1;
    end
  end
  hold on
end
title(['Window from ' Time_string(startpt) ' to ' Time_string(startpt+windowsize) ])
xlabel('Timestamps. (Click on Rt of fig to go forward, left to go back. Click HERE to quit.) ')
axis( [StartTime(Restrict(crtsd_array{1}, startpt,startpt+windowsize)) EndTime(Restrict(crtsd_array{1}, startpt,startpt+windowsize)) -ylimit ylimit]); 
%orient landscape
drawnow;
