function d = Filter_HFO(Fs,band,varargin)

d = designfilt('bandpassiir', ...       % Response type
       'StopbandFrequency1',band(1)-3, ...    % Frequency constraints
       'PassbandFrequency1',band(1), ...
       'PassbandFrequency2',band(2), ...
       'StopbandFrequency2',band(2)+3, ...
       'StopbandAttenuation1',60, ...   % Magnitude constraints
       'PassbandRipple',1, ...
       'StopbandAttenuation2',60, ...
       'DesignMethod','butter', ...      % Design method
       'MatchExactly','passband', ...   % Design method options
       'SampleRate',Fs);               % Sample rate

% freqz(d)
