%Vector_1way_CntlsDat.m  

% Copyright C 2009  Thomas A. Jones.  All rights reserved.
% Everyone is granted permission to copy, modify, and redistribute
% this program, but under the condition that this copyright notice
% remain intact and the Computers & Geosciences source be referenced. 
% This software has been tested extensively, but is distributed 
% WITHOUT ANY WARRANTY.  The author does not accept responsibility
% for any possible consequences of using it.

% GUI that obtains the columns numbers and ID for the samples 

% Variables to be obtained and defaults:
%   AzFrq = 0: If UseFrq=1, indicates number of column with Azimuths
%   X1 - X10 = 0: Column numbers containing azimuths (if UseFrq=0) or
%          frequency-counts (if Usefrq=1)
%   XName1 - XName10 = 'A' - 'J': Identifiers of the samples
%   RtrnCode = 0: Error return

% Set up the figure

Hfig_GUI = figure;       % Handle to figure window

set(Hfig_GUI, 'NumberTitle', 'off', ...
    'Color',[0.9, 0.9, 0.9], ...
    'Name','Specify category controls', ...
    'Menubar','none', ...
    'Units','inches',  ...
    'Position', [0.3, 0.4, 3.7, 6.4]);

% Set up the entries

if UseFrq == 1
    
    % count frequency data
    
HL_1 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 39, 60, 5], ...
    'String',['INPUT DATA IS IN FORM OF AZIMUTH CLASS MIDPOINTS', ...
              ' AND FREQUENCIES OF OCCURRENCE IN EACH CLASS']);

HL_AZ = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 36, 46, 3], ...
    'String',['Number of column that contains class midpoints of ', ...
             'Azimuths in file']);
HT_AZ = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.8, 0.8, 0.8], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[57, 37, 8, 2], ...
    'String',num2str(AzFrq), ...
    'Callback','AzFrq = str2num(get(HT_AZ,''String''));');

HL_X0A = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 33, 50, 2], ...
    'String','Category             Column containing');
HL_X0B = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 31.5, 50, 2], ...
    'String','Identifier                  Frequencies ');
else
    
    % individual azimuth data
    
HL_2 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 39, 65, 2], ...
    'String','INPUT DATA IS IN INDIVIDUAL AZIMUTHS');
 
HL_X0C = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 33, 70, 2], ...
    'String','Category            Column containing');
HL_X0D = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor',[0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 31.5, 70, 2], ...
    'String','Identifier                     Azimuths ');

end
    
HT_X1A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 29, 8, 2], ...
    'String',num2str(X1), ...
    'Callback','X1 = str2num(get(HT_X1A,''String''));');
HT_X1C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 29, 10, 2], ...
    'String',XName1, ...
    'Callback','XName1 = get(HT_X1C,''String'');');

HT_X2A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 27, 8, 2], ...
    'String',num2str(X2), ...
    'Callback','X2 = str2num(get(HT_X2A,''String''));');
HT_X2C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 27, 10, 2], ...
    'String',XName2, ...
    'Callback','XName2 = get(HT_X2C,''String'');');

HT_X3A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 25, 8, 2], ...
    'String',num2str(X3), ...
    'Callback','X3 = str2num(get(HT_X3A,''String''));');
HT_X3C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 25, 10, 2], ...
    'String',XName3, ...
    'Callback','XName3 = get(HT_X3C,''String'');');

HT_X4A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 23, 8, 2], ...
    'String',num2str(X4), ...
    'Callback','X4 = str2num(get(HT_X4A,''String''));');
HT_X4C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 23, 10, 2], ...
    'String',XName4, ...
    'Callback','XName4 = get(HT_X4C,''String'');');

HT_X5A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 21, 8, 2], ...
    'String',num2str(X5), ...
    'Callback','X5 = str2num(get(HT_X5A,''String''));');
HT_X5C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 21, 10, 2], ...
    'String',XName5, ...
    'Callback','XName5 = get(HT_X5C,''String'');');

HT_X6A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 19, 8, 2], ...
    'String',num2str(X6), ...
    'Callback','X6 = str2num(get(HT_X6A,''String''));');
HT_X6C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 19, 10, 2], ...
    'String',XName6, ...
    'Callback','XName6 = get(HT_X6C,''String'');');   

HT_X7A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 17, 8, 2], ...
    'String',num2str(X7), ...
    'Callback','X7 = str2num(get(HT_X7A,''String''));');
HT_X7C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 17, 10, 2], ...
    'String',XName7, ...
    'Callback','XName7 = get(HT_X7C,''String'');');  

HT_X8A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 15, 8, 2], ...
    'String',num2str(X8), ...
    'Callback','X8 = str2num(get(HT_X8A,''String''));');
HT_X8C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 15, 10, 2], ...
    'String',XName8, ...
    'Callback','XName8 = get(HT_X8C,''String'');');  

HT_X9A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 13, 8, 2], ...
    'String',num2str(X9), ...
    'Callback','X9 = str2num(get(HT_X9A,''String''));');
HT_X9C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 13, 10, 2], ...
    'String',XName9, ...
    'Callback','XName9 = get(HT_X9C,''String'');');  

HT_X10A = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[35, 11, 8, 2], ...
    'String',num2str(X10), ...
    'Callback','X10 = str2num(get(HT_X10A,''String''));');
HT_X10C = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 11, 10, 2], ...
    'String',XName10, ...
    'Callback','XName10 = get(HT_X10C,''String'');');  
                      
HPushCls = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 2, 10, 2], ...
    'String','OK', ...
    'Callback','RtrnCode = str2num(''0'');close;');
HPushCncl = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[50, 2, 10, 2], ...
    'String','Cancel', ...
    'Callback','RtrnCode = str2num(''8'');close;');

uiwait

