%Vector_1way_SpecCalcsG.m 

% Copyright C 2009  Thomas A. Jones.  All rights reserved.
% Everyone is granted permission to copy, modify, and redistribute
% this program, but under the condition that this copyright notice
% remain intact and the Computers & Geosciences source be referenced. 
% This software has been tested extensively, but is distributed 
% WITHOUT ANY WARRANTY.  The author does not accept responsibility
% for any possible consequences of using it.

% GUI that obtains the controls that specify
% the calculations to be made

% Variables to be obtained and defaults:
%   Flag1A=0: Test for equality of vector means if =1
%   Flag1B=0: Confidence interval on difference of vector means if =1
%   Flag2P=0: Generate plots if =1
%   Flag2A=0: Test for equality of concentrations, kappa, if =1
%   BSRS = 0: Do resampling calcs, even if not required by sample size
%   alfa=0.05: Signficance level; should be 0.001 <= alfa <= 0.25
%   NB=500:  Number bootstrap (resampling) trials
%   RtrnCode=0: Error return

% Set up the figure

Hfig_GUI = figure;       % Handle to figure window

set(Hfig_GUI, 'NumberTitle', 'off', ...
    'Color', [0.9, 0.9, 0.9], ... 
    'Name','Specify calculations to do', ...
    'Menubar','none', ...
    'Units','inches',  ...
    'Position', [0.3, 2.5, 5, 4.2]);

% Set up the entries

HC_FR = uicontrol(Hfig_GUI, 'Style','frame', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[8, 11, 82, 0.1]);

HC_INS1 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[8, 26.5, 65, 2], ...
    'String','Specify any, all, or none of these following options:');

HC_2P = uicontrol(Hfig_GUI, 'Style','checkbox', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 24, 70, 2], ...
    'Value', Flag2P, ...
    'String','Generate plots (rose diagrams of category data)', ...
    'Callback',['if get(HC_2P,''Value'') == 1,' ...
                  'Flag2P = str2num(''1'');,' ...
                'else,' ...
                  'Flag2P = str2num(''0'');,'...
                'end']);

HC_1A = uicontrol(Hfig_GUI, 'Style','checkbox', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 21, 65, 2], ...
    'Value', Flag1A, ...
    'String','Test equality of vector means', ...
    'Callback',['if get(HC_1A,''Value'') == 1,' ...
                  'Flag1A = str2num(''1'');,' ...
                'else,' ...
                  'Flag1A = str2num(''0'');,'...
                'end']);

HC_1B = uicontrol(Hfig_GUI, 'Style','checkbox', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 18, 65, 2], ...
    'Value', Flag1B, ...
    'String','Confidence interval on difference of vector means', ...
    'Callback',['if get(HC_1B,''Value'') == 1,' ...
                  'Flag1B = str2num(''1'');,' ...
                'else,' ...
                  'Flag1B = str2num(''0'');,'...
                'end']);
    
HC_2A = uicontrol(Hfig_GUI, 'Style','checkbox', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 15, 65, 2], ...
    'Value', Flag2A, ...
    'String','Test equality of concentrations, kappa', ...
    'Callback',['if get(HC_2A,''Value'') == 1,' ...
                  'Flag2A = str2num(''1'');,' ...
                'else,' ...
                  'Flag2A = str2num(''0'');,'...
                'end']);
            
HC_BS = uicontrol(Hfig_GUI, 'Style','checkbox', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ...
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 12, 75, 2], ...
    'Value', BSRS, ...
    'String','Make resampling calcs., even if N or Kappa is large', ...
    'Callback',['if get(HC_BS,''Value'') == 1,' ...
                  'BSRS = str2num(''1'');,' ...
                'else,' ...
                  'BSRS = str2num(''0'');,'...
                'end']);
       
HC_ALF1 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 8, 65, 2], ...
    'String','Significance level (alfa) for inference');
HC_ALF2 = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[72, 8, 16, 2], ...
    'String',num2str(alfa), ...
    'Callback','alfa = str2num(get(HC_ALF2,''String''));');

HC_TRL1 = uicontrol(Hfig_GUI, 'Style','text', ...
    'FontName','Arial',...
    'BackgroundColor', [0.9, 0.9, 0.9], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 5, 65, 2], ...
    'String','Number resampling (bootstrap) trials');
HC_TRL2 = uicontrol(Hfig_GUI, 'Style','edit', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units','characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[72, 5, 16, 2], ...
    'String', num2str(NB), ...
    'Callback','NB = str2num(get(HC_TRL2,''String''));');   

HPushCls = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[10, 2, 10, 2], ...
    'String','OK', ...
    'Callback','RtrnCode = str2num(''0'');close');

HPushCncl = uicontrol(Hfig_GUI, 'Style','push', ...
    'FontName','Arial',...
    'BackgroundColor', [0.95, 0.95, 0.95], ... 
    'Units', 'characters', 'Horizontalalignment','left', ...
    'FontSize',str2num('10'),  'FontUnits','points', ...
    'Position',[80, 2, 10, 2], ...
    'String','Cancel', ...
    'Callback','RtrnCode = str2num(''9'');close');

uiwait





